name: Deploy to Railway

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Railway
        uses: railwayapp/cli-action@v1
        with:
          command: "deploy --project project-id-goes-here"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
