name: Deploy to Railway

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-pocketbase:
    runs-on: ubuntu-latest
    outputs:
      pocketbase-url: ${{ steps.deploy-pb.outputs.url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy PocketBase to Railway
      id: deploy-pb
      uses: railway/deploy@v3
      with:
        service: ${{ secrets.RAILWAY_POCKETBASE_SERVICE_ID }}
        environment: production
        detach: false
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    - name: Wait for PocketBase to be ready
      run: |
        echo "Waiting for PocketBase service to be ready..."
        sleep 30
        # Extract URL from Railway deployment (this would be set by Railway)
        echo "POCKETBASE_URL=${{ steps.deploy-pb.outputs.url }}" >> $GITHUB_OUTPUT

  deploy-app:
    runs-on: ubuntu-latest
    needs: deploy-pocketbase
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'app/package-lock.json'

    - name: Install dependencies
      working-directory: ./app
      run: npm ci

    - name: Build with environment variables
      working-directory: ./app
      run: |
        export POCKETBASE_URL="${{ needs.deploy-pocketbase.outputs.pocketbase-url }}"
        npm run build
      env:
        POCKETBASE_URL: ${{ needs.deploy-pocketbase.outputs.pocketbase-url }}

    - name: Deploy Astro App to Railway
      uses: railway/deploy@v3
      with:
        service: ${{ secrets.RAILWAY_APP_SERVICE_ID }}
        environment: production
        detach: false
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        POCKETBASE_URL: ${{ needs.deploy-pocketbase.outputs.pocketbase-url }} 